import CustomAxios from "@/globalcomponents/CustomAxios";
import { initURL } from "../../BaseUrl";

const endpointCandidates = (path) => {
  const normalized = path.startsWith("/") ? path : `/${path}`;
  const withPrefix = initURL ? `/${initURL}${normalized}` : normalized;

  return [...new Set([withPrefix, normalized])];
};

const unwrap = (payload) => {
  if (payload && typeof payload === "object" && "data" in payload) {
    return payload.data;
  }

  return payload;
};

const requestWithFallback = async (method, path, data) => {
  let lastError = null;

  for (const candidate of endpointCandidates(path)) {
    try {
      const response = await CustomAxios({
        method,
        url: candidate,
        data,
      });

      return unwrap(response?.data);
    } catch (error) {
      lastError = error;
      const status = error?.response?.status;

      if (status && status !== 404) {
        break;
      }
    }
  }

  throw lastError;
};

export const businessContinuityApi = {
  getExecutive: () => requestWithFallback("get", "/bc/dashboard/executive"),
  getHeatmap: () => requestWithFallback("get", "/bc/dashboard/risk-heatmap"),
  getIncidentTrend: () =>
    requestWithFallback("get", "/bc/dashboard/incident-trend"),
  getVendorRisk: () => requestWithFallback("get", "/bc/dashboard/vendor-risk"),
  getDrillPerformance: () =>
    requestWithFallback("get", "/bc/dashboard/drill-performance"),
  getRiskTrend: () => requestWithFallback("get", "/bc/dashboard/risk-trend"),
  getAlerts: () => requestWithFallback("get", "/bc/dashboard/alerts"),
  createSnapshot: () => requestWithFallback("post", "/bc/dashboard/snapshot"),
  getEnterpriseResilience: () =>
    requestWithFallback("get", "/bc/resilience/enterprise"),
  getResilienceDashboard: () =>
    requestWithFallback("get", "/bc/resilience/dashboard"),
  getAssets: () => requestWithFallback("get", "/bc/assets"),
  createAsset: (payload) => requestWithFallback("post", "/bc/assets", payload),
  updateAsset: (id, payload) =>
    requestWithFallback("put", `/bc/assets/${id}`, payload),
  getProcesses: () => requestWithFallback("get", "/bc/processes"),
  createProcess: (payload) =>
    requestWithFallback("post", "/bc/processes", payload),
  updateProcess: (id, payload) =>
    requestWithFallback("put", `/bc/processes/${id}`, payload),
  calculateBia: (payload) => requestWithFallback("post", "/bia/calculate", payload),
  saveBia: (payload) => requestWithFallback("post", "/bia/save", payload),
  getBiaByProcess: (processId) =>
    requestWithFallback("get", `/bia/${processId}`),
  getRisks: () => requestWithFallback("get", "/bc/risks"),
  createRisk: (payload) => requestWithFallback("post", "/bc/risks", payload),
  updateRisk: (id, payload) =>
    requestWithFallback("put", `/bc/risks/${id}`, payload),
  getVendors: () => requestWithFallback("get", "/bc/vendors"),
  createVendor: (payload) =>
    requestWithFallback("post", "/bc/vendors", payload),
  updateVendor: (id, payload) =>
    requestWithFallback("put", `/bc/vendors/${id}`, payload),
  getDrPlans: () => requestWithFallback("get", "/dr/plans"),
  createDrPlan: (payload) =>
    requestWithFallback("post", "/dr/plans", payload),
  updateDrPlan: (id, payload) =>
    requestWithFallback("put", `/dr/plans/${id}`, payload),
  autoGenerateDrPlans: (processId) =>
    requestWithFallback("post", `/dr/plans/auto-generate/${processId}`),
};
